### PR TITLE
Add External Recruitment Checkbox

### PR DESCRIPTION
**Pull request by petabite**
### Administrative Info
Monday Board ID: 1181559666
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
- add a "can be assigned to pending users" checkbox to the role edit/create screen that is tied to the role's `external_recruitment` field from #61. 

### Testing
- edited and created a role and checked "can be assigned to pending users" and made sure the database reflected the change
- checked that the checkbox was auto selected for roles with `external_recruitment: true`.

### CODE REVIEW

**Review by hahsu — CHANGES_REQUESTED** [review]
Not too sure how this would look visually, but since external recruitment isn't really a permission, should we put the checkbox for it above the title that says external recruitment? Maybe we have a title that is like Properties and then under it external recruitment, and then the title Permissions, and then all the Permissions. What do you think?

**Comment by AnsonLee99** [comment]
> Not too sure how this would look visually, but since external recruitment isn't really a permission, should we put the checkbox for it above the title that says external recruitment? Maybe we have a title that is like Properties and then under it external recruitment, and then the title Permissions, and then all the Permissions. What do you think?

Yeah, I agree with this. The checkbox looks a bit weird being under the permissions.

**Comment by petabite** [comment]
True, that does look a bit weird. Were you thinking something like this?

**Comment by hahsu** [comment]
> True, that does look a bit weird. Were you thinking something like this?
> 
> 

Ah yes, this is what I was imagining

**Review by hahsu — APPROVED** [review]
lgtm, thanks!

**Review by AnsonLee99 — APPROVED** [review]
Lgtm!

**Pull request merged**
