### PR TITLE
Made phone number and GitHub username not required

### PR DESCRIPTION
**Pull request by zainnk902**
### Administrative Info
Monday Board ID: 1297642175
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
Made phone number and GitHub user name fields optional, not required

### Testing
How did you confirm your changes worked? 
I was able to make user without a phone number or GitHub username

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

Screen Shot 2021-05-26 at 4 50 52 AM

### CODE REVIEW

**Review by hahsu — APPROVED** [review]
lgtm, thanks! (Sorry, remembered a small change to be fixed).

**Review by hahsu — CHANGES_REQUESTED** [review]
Can we update this part of the code: https://github.com/TritonSE/TSE-Oktavian/blob/main/backend/services/users.js#L30
phone and github username should be able to be removed now since they are not required fields anymore.

**Review by petabite — APPROVED** [review]
LGTM

**Comment by hollyham** [comment]
> This PR is linked to [Item 1297642175](https://triton-software-engineering.monday.com/boards/1297642175/pulses/1297642175) on [Board 1297642175](https://triton-software-engineering.monday.com/boards/1297642175) and has now been put into Code Review status!

Board ID should be 1181559666 (right now it appears to be set to the task ID).

**Pull request merged**
