### PR TITLE
Feature/justinyaodu/1183384445 implement refresh route

### PR DESCRIPTION
**Pull request by justinyaodu**
Co-authored-by: Ly Nguyen kln014@ucsd.edu

### Administrative Info
Monday Board ID: 1181559666
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Add refresh token to User schema
- Attach refresh token in register and login routes
- Implement route to refresh

### Testing
How did you confirm your changes worked? 
- Tested using the frontend changes which refresh periodically

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

See other PR :)

### CODE REVIEW

**Review by petabite — CHANGES_REQUESTED** [review]
Looks solid to me! I did notice one thing, however. It looks like `refreshToken` is actually getting included in the payload of the JWT. A quick decode on jwt.io confirms this:

image

I'm not sure if you have already taken this into account anywhere (or it may not even be a problem at all), but theoretically, an attacker could steal a JWT via the XSS attack David mentioned in the task description and that would give them access to the `refreshToken` which they can then attach in a cookie (along with the stolen JWT in the request body) in a request to the `/api/auth/refresh` route and get new JWTs for that user forever. One way to fix this is to remove `refreshToken` from the User object being returned from the `toJSON` function in the User schema (like how password is being removed). But, other than that, everything else looks good!

Side note: Do you know why the entire user object is getting "signed" into the token payload? We may only just need the `_id` (which also solves the above issue) but there may be a reason for that I don't know about.

**Comment by justinyaodu** [comment]
I don't think it's possible for client-side JavaScript to set the refresh token cookie, since it's HTTP only, but I agree that having the entire User object present is unnecessary. I'll update it to only include the `_id` field, since that's all we're using.

**Review by petabite — APPROVED** [review]
👍

**Review by hahsu — APPROVED** [review]
lgtm!

**Pull request merged**
