### PR TITLE
Disable delete button for builtin roles

### PR DESCRIPTION
**Pull request by petabite**
### Administrative Info
Monday Board ID: 1181559666
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
- disabled delete button for builtin roles

### Confirmation of Change 

**not builtin role**

**builtin role**

### CODE REVIEW

**Comment by justinyaodu** [comment]
Wow, you made a lot of changes here! Are you sure you don't want to split it into two PRs :joy:

**Comment by petabite** [comment]
Ah shoot! You righttt. Hopefully Hannah and Benson won't have too much trouble figuring it all out

**Review by hahsu — APPROVED** [review]
lgtm, lots of complex logic going on here.

**Review by Benson272 — APPROVED** [review]
Good job on the PR, must've taken you a while to finish this

**Pull request merged**
